[repository]
name = "plone.palette"
managed_by_uv = false
changelog = "CHANGELOG.md"
version = "version.txt"
compose = "docker-compose.yml"

[repository.towncrier]
section = "Project"
settings = "towncrier.toml"

[backend]
path = "backend"

[backend.package]
name = "plone.palette"
path = "backend"
changelog = "backend/CHANGELOG.md"
towncrier_settings = "backend/pyproject.toml"
base_package = "Products.CMFPlone"
publish = false

[cookieplone]
template = "classic_project"
template_version = "e723d2d7bea1025300c58cd81a402cf995517756"
generated_date = "2026-05-29 10:11:36"
